INSERT INTO Events (name, description, imagePath)
VALUES
('Tech Summit 2024', 'An annual gathering of technology enthusiasts, professionals, and innovators to discuss the latest advancements in artificial intelligence, blockchain, and cloud computing.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-1.avif'),
('Art & Expression Workshop', 'A creative space for aspiring and professional artists to explore various forms of art, including painting, sculpting, and digital design, with expert-led sessions.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-2.avif'),
('Startup Incubator Demo Day', 'Showcasing the groundbreaking ideas of budding entrepreneurs, this event provides a platform for startups to pitch their innovations to investors and industry leaders.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-3.avif'),
('Global Health Conference', 'A platform for medical professionals, researchers, and policymakers to collaborate on addressing global health challenges, including pandemics, mental health, and innovative treatments.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-4.avif'),
('Culinary Arts Festival', 'An immersive experience into the world of gourmet cooking, featuring live cooking demonstrations, food-tasting sessions, and masterclasses by renowned chefs.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-5.avif'),
('Marathon for a Cause', 'A community-driven marathon aimed at raising funds for education, healthcare, and disaster relief. Participants enjoy a scenic route while supporting meaningful causes.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-6.avif'),
('Space Exploration Forum', 'A gathering of scientists, astronauts, and space enthusiasts to discuss the future of interstellar travel, planetary colonization, and technological advancements in astronomy.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-7.avif'),
('Film Appreciation Night', 'An evening dedicated to the art of cinema, featuring screenings of classic films, panel discussions with filmmakers, and a celebration of storytelling through visual media.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-8.avif'),
('Music in the Park', 'A vibrant outdoor event showcasing performances by local and international musicians across various genres, creating a joyful atmosphere for all ages.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-9.avif'),
('Sustainable Living Expo', 'An interactive expo focused on eco-friendly living, featuring workshops on renewable energy, sustainable farming, and reducing carbon footprints.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-10.avif'),
('History Reimagined', 'A unique event exploring historical milestones through interactive exhibits, live reenactments, and thought-provoking discussions with historians.', 'https://res.cloudinary.com/df3wjfv1t/image/upload/v1734823162/kkc-11.avif');